name: Build Windows App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: cd example && flutter pub get

#      - name: Enable Windows Desktop
#        run: flutter config --enable-windows-desktop

      - name: Build Windows App
        run: cd example && flutter build windows

#      - name: Upload Build Artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: windows-build
#          path: build/windows/runner/Release/
